name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: web-to-pdf-linux
            build_script: build-linux
          - os: windows-latest
            output_name: web-to-pdf-windows.exe
            build_script: build-windows
          - os: macos-latest
            output_name: web-to-pdf-macos
            build_script: build-macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "10.10.0"

      - name: Install dependencies
        run: pnpm install

      - name: Install Windows SDK
        if: matrix.os == 'windows-latest'
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 20348

      - name: Build executable
        run: node ${{ matrix.build_script }}.js
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: web-to-pdf*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            web-to-pdf-linux/web-to-pdf
            web-to-pdf-windows.exe/web-to-pdf.exe
            web-to-pdf-macos/web-to-pdf
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
